version: "2.1"

services:

  core:
    build: './core'
    command: 'true'
    restart: always

  metrics:
    build: ./metrics
    pid: host
    privileged: true
    network_mode: host
    restart: always
    labels:
      io.resin.features.balena-socket: '1'
      io.resin.features.dbus: '1'
