version: "2.1"

services:

  core:
    build: ./core
    command: "roscore"
    restart: always
    privileged: true
    network_mode: host
    tty: true

  metrics:
    build: ./metrics
    pid: host
    privileged: true
    network_mode: host
    restart: always
    labels:
      io.resin.features.balena-socket: '1'
      io.resin.features.dbus: '1'
