version: "2.1"

services:
  host:
    build: './host'
    command: "bash"
    privileged: true
    stdin_open: true
    tty: true
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      DISPLAY: $IP:0
      QT_X11_NO_MITSHM: '1'
