#!/usr/bin/env bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
set -ex
rm -rf $DIR/../../devhost/scratch/ros_lib
docker-compose -f $DIR/../../docker-compose.devhost.yml run shell rosrun rosserial_arduino make_libraries.py /root/scratch
sudo chown -R $USER:$USER $DIR/../../devhost/scratch/ros_lib
cp -r $DIR/../../devhost/scratch/ros_lib/{geometry_msgs,nav_msgs,ros,roscpp,rosserial_arduino,rosserial_msgs,sensor_msgs,std_msgs,std_srvs,tf,tf2_msgs,*.*} opencr_firmware/libraries/ros_lib/